import type { Metadata } from "next";
import "./globals.css";
import "../styles/styles.scss";
import Providers from "./Providers";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Portfolio New",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Header />
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
